# Generated by Django 5.2.4 on 2025-08-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('host', models.CharField(blank=True, max_length=128)),
                ('port', models.CharField(blank=True, max_length=128)),
            ],
        ),
    ]
