# Generated by Django 5.2.4 on 2025-08-12 12:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_user_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailXmlError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(blank=True)),
                ('received_from', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.IntegerField(blank=True, null=True)),
                ('decoded_ok', models.BooleanField(default=False)),
                ('xml_text', models.TextField(blank=True, null=True)),
                ('xml_base64', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('stacktrace', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.user')),
            ],
        ),
    ]
