# Generated by Django 5.2.4 on 2025-10-08 17:38

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(null=True, auto_now_add=True),
        ),
        migrations.AddField(
            model_name='user',
            name='office365',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='office365_client_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='office365_client_secret',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='office365_tenant_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(null=True, auto_now_add=True),
        ),
    ]
