# Generated by Django 5.2.4 on 2025-08-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emissor',
            old_name='name',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='emissor',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
