# Generated by Django 5.2.4 on 2025-08-01 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
        ('emissores', '0002_rename_name_emissor_nome_emissor_nome_fantasia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdc', models.CharField(max_length=48, unique=True)),
                ('est', models.CharField(blank=True, max_length=10, null=True)),
                ('pun_exp', models.CharField(blank=True, max_length=10, null=True)),
                ('num_doc', models.CharField(max_length=20)),
                ('fecha_emision', models.DateTimeField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emissor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissores.emissor')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.tipodocumento')),
            ],
        ),
    ]
