# Generated by Django 5.2.4 on 2025-08-01 18:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='documento_xml',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
