# Generated by Django 5.2.4 on 2025-09-16 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('documentos', '0003_documento_documento_xml'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
            preserve_default=False,
        ),
    ]
